### PR TITLE
Allow laravel 9.x

### PR DESCRIPTION
**Pull request by Koozza**
Updated composer to allow installs on laravel 9.x. Included php 8.0 to travis

### CODE REVIEW

**Comment by liepumartins** [comment]
@Koozza could You add PHP 8.1 also?

Travis fails because all php versions are in one "check".
Opening it reveals, that 5.6, 7.2, 7.3, 7.4 and 8.0 passes.
The ones that fail, does so because of configuration errors, not because of code.

@antonioribeiro please help with this. firewall package is awesome, but the support package blocks use with laravel 9 and php 8+

Much appreciated!

**Comment by jeromeatmirum** [comment]
Any update? We're trying to update our production apps to L9 and the firewall package is what's left. Thank you for this amazing package btw.

**Comment by liepumartins** [comment]
It is possible, that `xenial` is too old and `bionic` or even better `focal` should be used as Travis CI `dist`. 
I have seen other travis.yml files where `dist: ` is not configured at all, using default setting. Maybe that is better!

PHP 5.3 should be removed completely, as Travis CI does not support it since 2017 (only on dist: precise) and package itself requires PHP >=5.4

I hope that making these checks green we can attract @antonioribeiro attention to merge this.

**Comment by liepumartins** [comment]
Does not this require a new release, so the version can be referenced?

**Pull request merged**
